version: '3'

services:
  php:
    build: ./php
    ports:
      - "8081:80"

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  dbdata: null